// AUTO-GENERATED by packages/tokens/scripts/build-tokens.ts
// Source: packages/tokens/src/raw/*.json
// Do not edit by hand — run `pnpm --filter @field-ds/tokens build` to regenerate.

export const colour = {
  "text-n-icon": {
    primary: "#1d2539",
    secondary: "#475067",
    tertiary: "#666d85",
    muted: "#989fb3",
    "on-surface-bold": "#ffffff",
    "on-surface-subtle": "#ffffffcc",
    action: "#0f61ff",
    supermall: "#2122b8",
    error: "#d92626",
    warning: "#e5641a",
    "yellow-light": "#feee00",
    "yellow-dark": "#a36200",
    success: "#0f8857",
  },
  surface: {
    primary: "#ffffff",
    secondary: "#f9f9fb",
    tertiary: "#f2f3f7",
    muted: "#eaecf0",
    "tertiary-inverted": "#343d54",
    "secondary-inverted": "#1d2539",
    "primary-inverted": "#101628",
    "action-subtle": "#ebf4ff",
    "action-bold": "#0f7eff",
    "action-extrabold": "#0f61ff",
    "supermall-subtle": "#edeefd",
    "supermall-bold": "#2122b8",
    "error-subtle": "#fff0f0",
    "error-bold": "#d92626",
    "warning-subtle": "#fff1e0",
    "warning-bold": "#e5641a",
    "yellow-subtle": "#fefdc8",
    "yellow-mild": "#fff7c2",
    "brand-primary": "#feee00",
    "yellow-bold": "#f5c400",
    "success-subtle": "#e3fcf2",
    "success-bold": "#0f8857",
    "overlay-subtle": "#0000003d",
    "overlay-bold": "#000000cc",
  },
  border: {
    primary: "#eaecf0",
    subtle: "#f2f3f7",
    medium: "#d0d4dd",
    bold: "#666d85",
    extrabold: "#101628",
    action: "#bddbff",
    "action-bold": "#0f61ff",
    supermall: "#c0c2f6",
    error: "#fdb5b5",
    warning: "#fedbb4",
    yellow: "#fff7c2",
    success: "#adf0d5",
  },
} as const;
export type Colour = typeof colour;

export const font = {
  heading: {
    h40: {
      size: 40,
      "line-height": 48,
      "letter-spacing": -0.25,
    },
    h32: {
      size: 32,
      "line-height": 40,
      "letter-spacing": -0.25,
    },
    h28: {
      size: 28,
      "line-height": 36,
      "letter-spacing": -0.25,
    },
    h24: {
      size: 24,
      "line-height": 32,
      "letter-spacing": -0.25,
    },
    h20: {
      size: 20,
      "line-height": 28,
      "letter-spacing": -0.25,
    },
    h18: {
      size: 18,
      "line-height": 24,
      "letter-spacing": -0.15,
    },
    h16: {
      size: 16,
      "line-height": 20,
      "letter-spacing": -0.15,
    },
  },
  body: {
    b16: {
      size: 16,
      "line-height": 20,
      "letter-spacing": -0.15,
    },
    b14: {
      size: 14,
      "line-height": 18,
      "letter-spacing": -0.1,
    },
    b12: {
      size: 12,
      "line-height": 16,
      "letter-spacing": -0.1,
    },
    b11: {
      size: 11,
      "line-height": 14,
      "letter-spacing": -0.1,
    },
  },
  action: {
    a17: {
      size: 17,
      "line-height": 24,
      "letter-spacing": -0.25,
    },
    a16: {
      size: 16,
      "line-height": 24,
      "letter-spacing": 0,
    },
    a14: {
      size: 14,
      "line-height": 20,
      "letter-spacing": 0,
    },
    a12: {
      size: 12,
      "line-height": 16,
      "letter-spacing": 0,
    },
  },
} as const;
export type Font = typeof font;

export const space = {
  "0": 0,
  "1": 1,
  "2": 2,
  "4": 4,
  "6": 6,
  "8": 8,
  "10": 10,
  "12": 12,
  "14": 14,
  "16": 16,
  "18": 18,
  "20": 20,
  "24": 24,
  "28": 28,
  "32": 32,
  "36": 36,
  "40": 40,
  "44": 44,
  "48": 48,
  "52": 52,
  "56": 56,
  "60": 60,
  "64": 64,
  "72": 72,
  "-2": -2,
  "-4": -4,
  "-6": -6,
  "-8": -8,
  "-12": -12,
} as const;
export type Space = typeof space;

export const radius = {
  "0": 0,
  "2": 2,
  "4": 4,
  "6": 6,
  "8": 8,
  "10": 10,
  "12": 12,
  "14": 14,
  "16": 16,
  "18": 18,
  "20": 20,
  "24": 24,
  "28": 28,
  "32": 32,
  "36": 36,
  "40": 40,
  rounded: 9999,
} as const;
export type Radius = typeof radius;
