// AUTO-GENERATED by packages/tokens/scripts/build-tokens.ts
// Source: packages/tokens/src/raw/*.json
// Do not edit by hand — run `pnpm --filter @field-ds/tokens build` to regenerate.

// Minimal subset of react-native's TextStyle so this package stays RN-agnostic.
// Consumers can cast/widen to RN's TextStyle at the call site.
export type FieldTextStyle = {
  fontFamily: string;
  fontSize: number;
  fontWeight: "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
  lineHeight: number;
  letterSpacing: number;
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
  textDecorationLine?: "none" | "underline" | "line-through" | "underline line-through";
};

export const textStyles = {
  Heading_H40_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 40,
    fontWeight: "700",
    lineHeight: 48,
    letterSpacing: -0.25,
  },
  Heading_H40_Extrabold: {
    fontFamily: "Noontree-ExtraBold",
    fontSize: 40,
    fontWeight: "800",
    lineHeight: 48,
    letterSpacing: -0.25,
  },
  Heading_H32_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 32,
    fontWeight: "700",
    lineHeight: 40,
    letterSpacing: -0.25,
  },
  Heading_H32_Extrabold: {
    fontFamily: "Noontree-ExtraBold",
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 40,
    letterSpacing: -0.25,
  },
  Heading_H28_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 36,
    letterSpacing: -0.25,
  },
  Heading_H24_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 32,
    letterSpacing: -0.25,
  },
  Heading_H20_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 28,
    letterSpacing: -0.25,
  },
  Heading_H18_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 24,
    letterSpacing: -0.15,
  },
  Heading_H16_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  Body_B16_Regular: {
    fontFamily: "Noontree-Regular",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  Body_B16_Medium: {
    fontFamily: "Noontree-Medium",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  Body_B16_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  Body_B16_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  Body_B16_Strikethrough: {
    fontFamily: "Noontree-Regular",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: -0.15,
    textDecorationLine: "line-through",
  },
  Body_B14_Regular: {
    fontFamily: "Noontree-Regular",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: -0.1,
  },
  Body_B14_Medium: {
    fontFamily: "Noontree-Medium",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 18,
    letterSpacing: -0.1,
  },
  Body_B14_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 18,
    letterSpacing: -0.1,
  },
  Body_B14_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.1,
  },
  Body_B14_Strikethrough: {
    fontFamily: "Noontree-Regular",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: -0.1,
  },
  Body_B12_Regular: {
    fontFamily: "Noontree-Regular",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: -0.1,
  },
  Body_B12_Medium: {
    fontFamily: "Noontree-Medium",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
    letterSpacing: -0.1,
  },
  Body_B12_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: -0.1,
  },
  Body_B12_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
    letterSpacing: -0.1,
  },
  Body_B12_Strikethrough: {
    fontFamily: "Noontree-Regular",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: -0.1,
  },
  Body_B11_Regular: {
    fontFamily: "Noontree-Regular",
    fontSize: 11,
    fontWeight: "400",
    lineHeight: 14,
    letterSpacing: -0.1,
  },
  Body_B11_Medium: {
    fontFamily: "Noontree-Medium",
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 14,
    letterSpacing: -0.1,
  },
  Body_B11_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 14,
    letterSpacing: -0.1,
  },
  Body_B11_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
    letterSpacing: -0.1,
  },
  Body_B11_Strikethrough: {
    fontFamily: "Noontree-Regular",
    fontSize: 11,
    fontWeight: "400",
    lineHeight: 14,
    letterSpacing: -0.1,
  },
  Action_A17_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: -0.25,
  },
  Action_A16_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: 0,
  },
  Action_A16_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 24,
    letterSpacing: 0,
  },
  Action_A14_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    letterSpacing: 0,
  },
  Action_A14_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    letterSpacing: 0,
  },
  Action_A12_SemiBold: {
    fontFamily: "Noontree-SemiBold",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: 0,
  },
  Action_A12_Bold: {
    fontFamily: "Noontree-Bold",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
    letterSpacing: 0,
  },
} as const satisfies Record<string, FieldTextStyle>;

export type TextStyleName = keyof typeof textStyles;

export const Heading_H40_Bold = textStyles.Heading_H40_Bold;
export const Heading_H40_Extrabold = textStyles.Heading_H40_Extrabold;
export const Heading_H32_Bold = textStyles.Heading_H32_Bold;
export const Heading_H32_Extrabold = textStyles.Heading_H32_Extrabold;
export const Heading_H28_Bold = textStyles.Heading_H28_Bold;
export const Heading_H24_Bold = textStyles.Heading_H24_Bold;
export const Heading_H20_Bold = textStyles.Heading_H20_Bold;
export const Heading_H18_Bold = textStyles.Heading_H18_Bold;
export const Heading_H16_Bold = textStyles.Heading_H16_Bold;
export const Body_B16_Regular = textStyles.Body_B16_Regular;
export const Body_B16_Medium = textStyles.Body_B16_Medium;
export const Body_B16_SemiBold = textStyles.Body_B16_SemiBold;
export const Body_B16_Bold = textStyles.Body_B16_Bold;
export const Body_B16_Strikethrough = textStyles.Body_B16_Strikethrough;
export const Body_B14_Regular = textStyles.Body_B14_Regular;
export const Body_B14_Medium = textStyles.Body_B14_Medium;
export const Body_B14_SemiBold = textStyles.Body_B14_SemiBold;
export const Body_B14_Bold = textStyles.Body_B14_Bold;
export const Body_B14_Strikethrough = textStyles.Body_B14_Strikethrough;
export const Body_B12_Regular = textStyles.Body_B12_Regular;
export const Body_B12_Medium = textStyles.Body_B12_Medium;
export const Body_B12_SemiBold = textStyles.Body_B12_SemiBold;
export const Body_B12_Bold = textStyles.Body_B12_Bold;
export const Body_B12_Strikethrough = textStyles.Body_B12_Strikethrough;
export const Body_B11_Regular = textStyles.Body_B11_Regular;
export const Body_B11_Medium = textStyles.Body_B11_Medium;
export const Body_B11_SemiBold = textStyles.Body_B11_SemiBold;
export const Body_B11_Bold = textStyles.Body_B11_Bold;
export const Body_B11_Strikethrough = textStyles.Body_B11_Strikethrough;
export const Action_A17_SemiBold = textStyles.Action_A17_SemiBold;
export const Action_A16_SemiBold = textStyles.Action_A16_SemiBold;
export const Action_A16_Bold = textStyles.Action_A16_Bold;
export const Action_A14_SemiBold = textStyles.Action_A14_SemiBold;
export const Action_A14_Bold = textStyles.Action_A14_Bold;
export const Action_A12_SemiBold = textStyles.Action_A12_SemiBold;
export const Action_A12_Bold = textStyles.Action_A12_Bold;
