/**
 * Reads every SVG in ../src/svg/ and emits a single RN-friendly data module
 * (../src/icons-data.ts) plus the IconName type.
 *
 * The runtime <Icon name="..."> component (../src/Icon.tsx) reads from this
 * module and renders react-native-svg <Path> nodes. Per-path fill is
 * recolored from the canonical "#1D2539" to the consumer-supplied `color`.
 *
 * Run:
 *   pnpm --filter @field-ds/icons build
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SVG_DIR = resolve(__dirname, "../src/svg");
const OUT_FILE = resolve(__dirname, "../src/icons-data.ts");

const PATH_RE = /<path[^>]*\sd="([^"]+)"/g;

const files = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith(".svg"))
  .sort();

if (files.length === 0) {
  console.warn("No SVGs found — run `pnpm fetch:icons` first.");
}

const entries: { slug: string; paths: string[] }[] = [];
for (const f of files) {
  const slug = basename(f, ".svg");
  const svg = readFileSync(resolve(SVG_DIR, f), "utf8");
  const paths: string[] = [];
  let m: RegExpExecArray | null;
  PATH_RE.lastIndex = 0;
  while ((m = PATH_RE.exec(svg)) !== null) paths.push(m[1]);
  entries.push({ slug, paths });
}

const banner =
  `// AUTO-GENERATED by packages/icons/scripts/svg-to-rn.ts\n` +
  `// Source: packages/icons/src/svg/*.svg\n` +
  `// Do not edit by hand — run \`pnpm --filter @field-ds/icons build\` to regenerate.\n\n`;

const body =
  `export const iconPaths = {\n` +
  entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.slug)}: [${e.paths.map((p) => JSON.stringify(p)).join(", ")}],`,
    )
    .join("\n") +
  `\n} as const;\n\n` +
  `export type IconName = keyof typeof iconPaths;\n\n` +
  `export const iconNames: IconName[] = [\n` +
  entries.map((e) => `  ${JSON.stringify(e.slug)},`).join("\n") +
  `\n] as IconName[];\n`;

writeFileSync(OUT_FILE, banner + body);
console.log(`✔ Wrote ${entries.length} icons → ${OUT_FILE}`);
